### ISSUE TITLE
Supporting importing Apache UIMA XMI zip file

### ISSUE THREAD

**Issue by fishfree** [korpling/pepper#150]
See [this post](https://groups.google.com/g/inception-users/c/_orVHVT5aSM) first please.

It would most wonderful to co-work between INCEpTION & ANNIS!

**Comment by amir-zeldes** [comment]
If this is for Inception, probably the easiest way would be to not use UIMA but go over WebAnno TSV export instead:

https://github.com/korpling/pepperModules-WebannoTSVModules

I can post to the Inception forum too.

**Comment by amir-zeldes** [comment]
Hm, actually looks like I can't post it there - if this works for you, you may want to post the link above on the Inception group too.

**Comment by fishfree** [comment]
@amir-zeldes Yes, you need request to join [the Google group](https://groups.google.com/g/inception-users) first.
I tried WebAnno TSV before posting this issue. It lost lots of annotation layers after converting and importing into ANNIS, in other words, ANNIS lacks supporting some layers in WebAnno TSV files.

**Comment by fishfree** [comment]
@amir-zeldes Thank you! I will have a try.

**Comment by reckart** [comment]
@amir-zeldes the WebAnno TSV 3.3 files used in the GUM coref layer continue to be invalid. See

* https://github.com/amir-zeldes/gum/issues/101
* https://github.com/inception-project/inception/issues/4006#issuecomment-1550764925

**Comment by amir-zeldes** [comment]
That is correct - GUM uses a slightly older format from when we used Inception to annotate entities and coref. I think the issues @reckart linked to could be resolved by editing the files to fit the 3.3 spec, but are we sure that is the problem @fishfree is facing? I don't actually think they are trying to get GUM files into Inception, and since we don't use Inception or WebAnno to annotate the data anymore, there is probably no benefit to messing with the GUM data. 

If someone wants to expand the Pepper importer to support the format variation in the issues, that would be nice of course.

**Comment by amir-zeldes** [comment]
Mm, for the tool I would agree - a Pepper module called WebAnnoTSVImporter should probably be able to import that format moving forward. Adding @thomaskrause - are you aware of users for whom this might be important? It seems the current Pepper importer does not support the format correctly in the scenario described at the links above. It is probably not a huge upgrade for the module, but I am still not clear if the issue linked to above is @fishfree 's problem, so maybe they can clarify if this is even the problem.

For the corpus, if we're talking about GUM that's less clear: the only reason the format is in there at the moment is legacy, and the fact that a lot of scripts around the corpus consume that format; but they actually consume the older format version, and updating them all for eternity to keep in line with a tool not being used to build the corpus would be a big ask. Most users of GUM probably get it from the UD repo, where the same information is represented in the CoNLL-U format. I don't know of people importing GUM's tsv data for further annotation using Inception (I could be wrong of course 😅)

**Comment by reckart** [comment]
Mind that on the INCEpTION side of things, WebAnno TSV is also becoming a legacy format. The recommended format for INCEpTION users these days is UIMA CAS XMI or the new UIMA CAS JSON.

**Comment by amir-zeldes** [comment]
>If GUM is using features of CoNLL-U that are not yet supported and that people need, it would be on our side at INCEpTION/DKPro Core to look into improving that

Some things in GUM's conllu are probably idiosyncratic (for example representation of discourse relations), but other aspects might be nice to support, for example the Entity annotations which look like this and are a series of key-values on spans:

```CoNLL-U
# global.Entity = GRP-etype-infstat-centering-minspan-link-identity
...
1	For	for	ADP	IN	_	4	case	4:case	Discourse=joint-sequence_m:104->98:2
2	the	the	DET	DT	Definite=Def|PronType=Art	4	det	4:det	Bridge=173<188|Entity=(188-event-acc:inf-cf6-3,6,8-sgl
3	second	second	ADJ	JJ	Degree=Pos|NumType=Ord	4	amod	4:amod	_
4	campaign	campaign	NOUN	NN	Number=Sing	16	obl	16:obl:for	_
5	in	in	ADP	IN	_	10	case	10:case	_
6	the	the	DET	DT	Definite=Def|PronType=Art	10	det	10:det	Entity=(173-abstract-giv:inact-cf3-2,4,5-coref
7	Always	Always	ADV	NNP	Number=Sing	8	advmod	8:advmod	XML=<hi rend:::"italic">
8	Keep	Keep	PROPN	NNP	Number=Sing	10	compound	10:compound	_
9	Fighting	Fighting	PROPN	NNP	Number=Sing	8	xcomp	8:xcomp	XML=</hi>
10	series	series	NOUN	NN	Number=Sing	4	nmod	4:nmod:in	Entity=173)
11	in	in	ADP	IN	_	12	case	12:case	_
12	April	April	PROPN	NNP	Number=Sing	4	nmod	4:nmod:in	Entity=(189-time-new-cf10-1-sgl|XML=<date when:::"2015-04">
13	2015	2015	NUM	CD	NumForm=Digit|NumType=Card	12	nmod:tmod	12:nmod:tmod	Entity=(175-time-giv:inact-cf5-1-coref)189)188)|SpaceAfter=No|XML=</date>
```

This is the format used by the entire [CorefUD](https://ufal.mff.cuni.cz/corefud) project, so there are many datasets that use `Entity=` like this, with nested brackets, and popular APIs like udapy also support and (de)serialize this notation. 

> WebAnno TSV is also becoming a legacy format

This is maybe a reason to rather leave this alone, rather than trying to keep things in line with the current version of Inception... We should probably look into doing everything with conllu, but there is a lot of legacy code that expects this tsv to be available. I know there is now a new project in France looking to do UD data like GUM and annotating NER and other things on top of syntax with Inception, and it seems they want to represent things in conllu, so maybe that is the multilayer plain text format of the future?
