### ISSUE TITLE
[gui] cannot use path chooser

### ISSUE THREAD

**Issue by MartinKl** [korpling/pepper#45]
According to my research browsers do not allow access to the client's file system, so we cannot use a path chooser in the importers window to tell where to look for the corpus data. I guess, we'll have to ask the user to provide a zip file.
As a consequence I ask myself, if we could still use the workflow file xml format to save the workflow configuration.

**Comment by FlorianZipser** [comment]
I feared, that this could happen but still hope, that there is a workaround. In that specific case, we do not need a normal file upload dialogue, because we don't want to upload files, we just need to know a path, so may be there is another dialogue to do this. Pepper itself is running on the local mashine and will have full access to the data. The only problem is for the user to locate the im- and export path.

**Comment by MartinKl** [comment]
The decision has been the following:

There will be two versions of pepper gui. One version, where the host server is localhost, where we use a constructed path chooser based on FilesystemContainer and another version for host!=localhost. For the latter case we use file upload (zip).
